export type RiskLevel = "low" | "moderate" | "high" | "critical" | "unknown";

export interface Camera { id: string; name: string; status: string; risk_level: RiskLevel; media_url: string | null; source_type?: "file" | "youtube"; embed_url?: string; external?: boolean }
export interface HazardEvent { type: string; severity: RiskLevel; description: string; evidence: string[]; confidence: number }
export interface Assessment { camera_id: string; analysis_status: string; risk_level: RiskLevel; events: HazardEvent[]; audio_observations: {type: string; description: string; confidence: number}[]; environment: {risk_level: RiskLevel; factors: string[]; summary: string}; public_warning: string | null; reasoning_summary: string; errors: string[] }
export interface Alert extends HazardEvent { id: string; camera_id: string; acknowledged: boolean; created_at: string }
export interface TimelineEvent { id: string; timestamp: string; category: string; message: string; camera_id?: string; severity?: string; details?: Record<string, unknown> }
export interface Ocean { station_id: string; source: string; wave_height_ft: number | null; dominant_period_sec: number | null; average_period_sec: number | null; wave_direction_deg: number | null; wind_speed_mph: number | null; wind_gust_mph: number | null; water_temp_f: number | null; is_mock: boolean; status_message?: string }
export interface Weather { source: string; temperature_f: number | null; wind_speed_mph: number | null; wind_gust_mph: number | null; wind_direction_deg: number | null; visibility_m: number | null; condition: string; is_mock: boolean; status_message?: string }
export interface OceanRiskAssessment { risk_level: RiskLevel; factors: string[]; summary: string; sources: string[]; source_mode: "live" | "demo"; updated_at: string }
export interface LiveStatus { enabled: boolean; phase: string; video_id: string; watch_url: string; embed_url: string; interval_seconds: number; capture_seconds: number; last_capture: {captured_at?: string; video_frames?: number; audio_seconds?: number} | null; last_assessment: Assessment | null; next_analysis_at: string | null; error: string | null; environment_mode: "sensor_fusion"; dependencies: {ready: boolean; yt_dlp: boolean; av: boolean; python_executable: string; install_command: string} }
export interface DashboardStatus { global_status: string; cameras: Camera[]; assessments: Record<string, Assessment>; alerts: Alert[]; events: TimelineEvent[]; warning: {camera_id?: string; message: string; issued: boolean} | null; escalation: {camera_id: string; severity: string; reason: string} | null; ocean: Ocean; weather: Weather; ocean_risk_assessment: OceanRiskAssessment; gemma: {loaded: boolean; device: string; error?: string}; live: LiveStatus }
